[package]
name = "sorted-json"
version = "0.1.0"
authors = ["Amit Upadhyay <amitu@acko.com>"]
description = "a rust json serializer that sorts keys"
license = "BSD"

[dependencies]
serde_json = "~1.0.9"
itertools = "~0.7.8"
